export type AdeAutomationErrorCode =
  | 'ADE_DRY_RUN_DISABLED'
  | 'ADE_DRY_RUN_BUSY'
  | 'ADE_INTERNAL_AUTH_REQUIRED'
  | 'ADE_CONFIGURATION_INVALID'
  | 'ADE_SESSION_REQUIRED'
  | 'ADE_SESSION_INVALID'
  | 'ADE_SESSION_PATH_REQUIRED'
  | 'ADE_SESSION_PATH_INVALID'
  | 'ADE_BROWSER_UNAVAILABLE'
  | 'ADE_NAVIGATION_FAILED'
  | 'ADE_SELECTOR_PROFILE_INVALID'
  | 'ADE_MARKER_NOT_FOUND'
  | 'ADE_CIE_CREDENTIALS_REQUIRED'
  | 'ADE_CIE_CREDENTIALS_INVALID'
  | 'ADE_AUTH_PROFILE_REQUIRED'
  | 'ADE_AUTH_PROFILE_INVALID'
  | 'ADE_CIE_ENTRY_NOT_FOUND'
  | 'ADE_CIE_LEVEL2_NOT_FOUND'
  | 'ADE_CIE_USERNAME_FIELD_NOT_FOUND'
  | 'ADE_CIE_PASSWORD_FIELD_NOT_FOUND'
  | 'ADE_CIE_SUBMIT_NOT_FOUND'
  | 'ADE_CIE_MFA_NOT_STARTED'
  | 'ADE_CIE_MFA_TIMEOUT'
  | 'ADE_CIE_AUTH_BUSY'
  | 'ADE_PORTAL_FLOW_MISMATCH'
  | 'ADE_INCARICANTE_NOT_FOUND'
  | 'ADE_DOCUMENT_INPUT_INVALID'
  | 'ADE_DOCUMENT_DRY_RUN_BUSY'
  | 'ADE_DOCUMENT_FLOW_MISMATCH'
  | 'ADE_DOCUMENT_VERIFY_MISMATCH'
  | 'ADE_DOCUMENT_CONFIRMATION_BOUNDARY_NOT_FOUND';

export type AdeAutomationErrorCategory =
  | 'CONFIGURATION'
  | 'AUTH_REQUIRED'
  | 'BROWSER'
  | 'NAVIGATION'
  | 'SELECTOR_MISMATCH';

export class AdeAutomationError extends Error {
  constructor(
    message: string,
    readonly code: AdeAutomationErrorCode,
    readonly category: AdeAutomationErrorCategory,
    readonly retrySafe: boolean,
  ) {
    super(message);
    this.name = 'AdeAutomationError';
  }
}
